config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get '/categories/:category_id/news/:news_id', to: 'categories#news' ,as: 'categor_news'

    resources :categories
    resources :news

  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get 'homes/index'
  get 'homes/:id', to: 'homes#show', as: 'show_home'

  root 'homes#index'

  namespace :editor do
    
    resources  :news
  end



  namespace :admin do
   
    
    resources :categories

    get '/categories/:category_id/news/:news_id', to: 'categories#news' ,as: 'categor_news'

    resources :news do
      collection do
        get :search
      end
    end
    

   
  resources :states do
      resources :cities
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "news#index"

  
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :state
  belongs_to :city
  belongs_to :category
  has_many_attached :images
   has_many_attached :videos

  def image_urls
    images.map do |image|
      Rails.application.routes.url_helpers.rails_blob_url(image, only_path: true)
    end
  end
  # validates :title, presence: { message: "Title can't be blank" },
  # length: { maximum: 50, message: "Title is too long (maximum is 50 characters)" }
  # validates :headlines, presence: { message: "Title can't be blank" },
  # length: { maximum: 50, message: "Title is too long (maximum is 50 characters)" }


end

app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
  before_action :authenticate_user!
 before_action :check_admin_and_editor_roles
    before_action :set_news, only: [:show, :edit, :update, :destroy]
  
    def index
      @news = News.all
     
      # render json: @news, methods: [:image_urls]
    end
  
    def new
      @news = News.new
    end
  
    def create
      
      @news = News.create(news_params)
  
      
        redirect_to admin_news_index_path, notice: 'News was successfully created.'
      
     
    end
  
    def show
    end
  
    def edit
    end
  
    def update
      if @news.update(news_params)
        redirect_to admin_news_index_path, notice: 'News was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @news.destroy
      redirect_to admin_news_index_path, notice: 'News was successfully destroyed.'
    end
  
    private
  
    def set_news
      @news = News.find(params[:id])
    end
  
    def news_params
      params.require(:news).permit(:title, :headlines, :short_description, :description,:state_id ,:city_id ,:category_id, images: [] , videos: [])
    end

    def check_admin_and_editor_roles
      check_role
    end
  def check_role
    unless current_user.has_role?(:admin)
      redirect_to root_path, alert: "You are not authorized to access the editor panel."
    end
  end
end

app/controllers/api/news_controller.rb
class Api::NewsController < ApplicationController

     def index
      @news = News.all
     
      render json: @news, methods: [:image_urls]
    end

    def show
      @news = News.find(params[:id])
      render json: @news, methods: [:image_urls]


    end
 
end

app/controllers/editor/news_controller.rb
class Editor::NewsController < ApplicationController
  before_action :authenticate_user!
 before_action :check_admin_and_editor_roles
  
  def index
   
    @news = News.all
   
  end

  def new
    @news = News.new
  end

  def create
    
    @news = News.create(news_params)

    
      redirect_to editor_news_index_path, notice: 'News was successfully created.'
    
   
  end

  def show
    @news = News.find(params[:id])

  end

  def edit
    @news = News.find(params[:id])

  end

  def update
    if @news.update(news_params)
      redirect_to editor_news_index_path, notice: 'News was successfully updated.'
    else
      render :edit
    end
  end



  def news_params
    params.require(:news).permit(:title, :headlines, :short_description, :description,:state_id ,:city_id ,:category_id, images: [])
  end
 
  def check_admin_and_editor_roles
    check_role
  end
def check_role
    unless current_user.has_role?(:editor)
      redirect_to root_path, alert: "You are not authorized to access this page."
    end
  end



 
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/helpers/api/news_helper.rb
module Api::NewsHelper
end

app/helpers/editor/news_helper.rb
module Editor::NewsHelper
end

app/views/admin/news/_form.html.erb
<div class="sidebar">


      <form class="d-flex" role="search">
      <%= form_tag search_admin_news_index_path method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search news..." , class:"form-control me-2" %>
        <%= submit_tag "Search", class:"btn btn-outline-success" %>
      <% end %>
      </form>
  <a href="#">Field</a>
  <a href="#">City</a>
  <a href="#">Category</a>
  <a href="#">News</a>
  <a href="#">State</a>

  <%if user_signed_in?%>
  <%= link_to "logout" ,destroy_user_session_path,data: {"turbo-method": :delete}  ,class:"nav-link" %>
  <%else%>
  <%= link_to "login" ,new_user_session_path  ,class:"nav-link" %>

    <%end%>
</div>

<div class="form-container">
<%= form_with(model: @news, url: @news.new_record? ? admin_news_index_path : admin_news_path(@news), method: @news.new_record? ? :post : :patch) do |f| %>
 
  
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  
    <div class="field">
      <%= f.label :headlines %>
      <%= f.text_field :headlines %>
    </div>
  
    <div class="field">
      <%= f.label :short_description %>
      <%= f.text_area :short_description %>
    </div>
  
    

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>


    <div  >
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div  >
    <%= f.label :state_id %><br>
    <%= f.collection_select :state_id, State.all, :id, :name %>
  </div>
  <div>
       
    


      <%= f.label :city_id %><br>
      <%= f.collection_select :city_id,  City.all, :id, :name %>
    </div>
  

    <div>
         <%= f.label :images, 'Upload Images' %>
           <%= f.file_field :images, multiple: true %>
      </div>
      <div class="field">
    <%= f.label :videos, 'Upload Videos' %>
    <%= f.file_field :videos, multiple: true %>
  </div>
    <div class="btn btn-primary">
      <%= f.submit %>
    </div>
  <% end %>
  </div>

app/views/admin/news/edit.html.erb
<h1>Edit News</h1>

<div class="sidebar">


      <form class="d-flex" role="search">
      <%= form_tag search_admin_news_index_path method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search news..." , class:"form-control me-2" %>
        <%= submit_tag "Search", class:"btn btn-outline-success" %>
      <% end %>
      </form>
  <a href="#">Field</a>
  <a href="#">City</a>
  <a href="#">Category</a>
  <a href="#">News</a>
  <a href="#">State</a>

  <%if user_signed_in?%>
  <%= link_to "logout" ,destroy_user_session_path,data: {"turbo-method": :delete}  ,class:"nav-link" %>
  <%else%>
  <%= link_to "login" ,new_user_session_path  ,class:"nav-link" %>

    <%end%>
</div>
<%= form_for(@news, url: admin_news_path(@news), method: :patch) do |f| %>   



    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  
    <div class="field">
      <%= f.label :headlines %>
      <%= f.text_field :headlines %>
    </div>
  
    <div class="field">
      <%= f.label :short_description %>
      <%= f.text_area :short_description %>
    </div>
  
    

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>


    <div  class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div  class="field">
    <%= f.label :state_id %><br>
    <%= f.collection_select :state_id, State.all, :id, :name %>
  </div>
  <div class="field">
      <%= f.label :city_id %><br>
      <%= f.collection_select :city_id,  City.all, :id, :name %>
    </div>
    <div class="field">
    <%= f.label :images, 'Upload Images' %>
    <%= f.file_field :images, multiple: true, accept: 'image/*' %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Show', admin_news_path(@news) %> |
<%= link_to 'Back', admin_news_index_path %>

app/views/admin/news/index.html.erb
<h1>Admin Pannel</h1>


<div class="sidebar">


      <form class="d-flex" role="search">
      <%= form_tag search_admin_news_index_path method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search news..." , class:"form-control me-2" %>
        <%= submit_tag "Search", class:"btn btn-outline-success" %>
      <% end %>
      </form>
  <a href="#">Field</a>
  <a href="#">City</a>
  <a href="#">Category</a>
  <a href="#">News</a>
  <a href="#">State</a>

  <%if user_signed_in?%>
  <%= link_to "logout" ,destroy_user_session_path,data: {"turbo-method": :delete}  ,class:"nav-link" %>
  <%else%>
  <%= link_to "login" ,new_user_session_path  ,class:"nav-link" %>

    <%end%>
</div>
<div class="content">
<table  >
  <thead>
    <tr>
      <th>Title</th>
      <th>Headlines</th>
      <th>created_at</th>
      <th>Actions</th>

    </tr>
  </thead>
  <tbody>
    <% @news.each do |news| %>
      <tr >
        <td><%= news.title %></td>
        <td><%= news.headlines %></td>
        <td><%= display_ist_time(news.created_at) %></td>


        <td>
          <%= link_to 'Show', admin_news_path(news) %>
          <%= link_to 'Edit', edit_admin_news_path(news) %>
          <%= link_to 'Destroy', admin_news_path(news),data: {"turbo-method": :delete}%>
        
        </td>
      </tr>
    <% end %>
     
  </tbody>
</div>
   <div>
   <%= link_to 'New  category', new_admin_category_path %>
   <%= link_to 'New  state', new_admin_state_path %>
   </div>
</table>


<div class="button-container">
<%= link_to 'New News', new_admin_news_path, class: 'new-news-button' %>
</div>







	<!-- for header part -->
	<header>

		<div class="logosec">
			<div class="logo">GeeksForGeeks</div>
			<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210182541/Untitled-design-(30).png"
				class="icn menuicn"
				id="menuicn"
				alt="menu-icon">
		</div>

		<div class="searchbar">
			<input type="text"
				placeholder="Search">
			<div class="searchbtn">
			<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210180758/Untitled-design-(28).png"
					class="icn srchicn"
					alt="search-icon">
			</div>
		</div>

		<div class="message">
			<div class="circle"></div>
			<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210183322/8.png"
				class="icn"
				alt="">
			<div class="dp">
			<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210180014/profile-removebg-preview.png"
					class="dpicn"
					alt="dp">
			</div>
		</div>

	</header>

	<div class="main-container">
		<div class="navcontainer">
			<nav class="nav">
				<div class="nav-upper-options">
					<div class="nav-option option1">
						<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210182148/Untitled-design-(29).png"
							class="nav-img"
							alt="dashboard">
						<h3> Dashboard</h3>
					</div>

					<div class="option2 nav-option">
						<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210183322/9.png"
							class="nav-img"
							alt="articles">
						<h3> Articles</h3>
					</div>

					<div class="nav-option option3">
						<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210183320/5.png"
							class="nav-img"
							alt="report">
						<h3> Report</h3>
					</div>

					<div class="nav-option option4">
						<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210183321/6.png"
							class="nav-img"
							alt="institution">
						<h3> Institution</h3>
					</div>

					<div class="nav-option option5">
						<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210183323/10.png"
							class="nav-img"
							alt="blog">
						<h3> Profile</h3>
					</div>

					<div class="nav-option option6">
						<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210183320/4.png"
							class="nav-img"
							alt="settings">
						<h3> Settings</h3>
					</div>

					<div class="nav-option logout">
						<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210183321/7.png"
							class="nav-img"
							alt="logout">
						<h3>Logout</h3>
					</div>

				</div>
			</nav>
		</div>
		<div class="main">

			<div class="searchbar2">
				<input type="text"
					name=""
					id=""
					placeholder="Search">
				<div class="searchbtn">
				<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210180758/Untitled-design-(28).png"
						class="icn srchicn"
						alt="search-button">
				</div>
			</div>

			<div class="box-container">

				<div class="box box1">
					<div class="text">
						<h2 class="topic-heading">60.5k</h2>
						<h2 class="topic">Article Views</h2>
					</div>

					<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210184645/Untitled-design-(31).png"
						alt="Views">
				</div>

				<div class="box box2">
					<div class="text">
						<h2 class="topic-heading">150</h2>
						<h2 class="topic">Likes</h2>
					</div>

					<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210185030/14.png"
						alt="likes">
				</div>

				<div class="box box3">
					<div class="text">
						<h2 class="topic-heading">320</h2>
						<h2 class="topic">Comments</h2>
					</div>

					<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210184645/Untitled-design-(32).png"
						alt="comments">
				</div>

				<div class="box box4">
					<div class="text">
						<h2 class="topic-heading">70</h2>
						<h2 class="topic">Published</h2>
					</div>

					<img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210185029/13.png" alt="published">
				</div>
			</div>

			<div class="report-container">
				<div class="report-header">
					<h1 class="recent-Articles">Recent Articles</h1>
					<button class="view">View All</button>
				</div>

				<div class="report-body">
					<div class="report-topic-heading">
						<h3 class="t-op">Article</h3>
						<h3 class="t-op">Views</h3>
						<h3 class="t-op">Comments</h3>
						<h3 class="t-op">Status</h3>
					</div>

					<div class="items">
						<div class="item1">
							<h3 class="t-op-nextlvl">Article 73</h3>
							<h3 class="t-op-nextlvl">2.9k</h3>
							<h3 class="t-op-nextlvl">210</h3>
							<h3 class="t-op-nextlvl label-tag">Published</h3>
						</div>

						<div class="item1">
							<h3 class="t-op-nextlvl">Article 72</h3>
							<h3 class="t-op-nextlvl">1.5k</h3>
							<h3 class="t-op-nextlvl">360</h3>
							<h3 class="t-op-nextlvl label-tag">Published</h3>
						</div>

						<div class="item1">
							<h3 class="t-op-nextlvl">Article 71</h3>
							<h3 class="t-op-nextlvl">1.1k</h3>
							<h3 class="t-op-nextlvl">150</h3>
							<h3 class="t-op-nextlvl label-tag">Published</h3>
						</div>

						<div class="item1">
							<h3 class="t-op-nextlvl">Article 70</h3>
							<h3 class="t-op-nextlvl">1.2k</h3>
							<h3 class="t-op-nextlvl">420</h3>
							<h3 class="t-op-nextlvl label-tag">Published</h3>
						</div>

						<div class="item1">
							<h3 class="t-op-nextlvl">Article 69</h3>
							<h3 class="t-op-nextlvl">2.6k</h3>
							<h3 class="t-op-nextlvl">190</h3>
							<h3 class="t-op-nextlvl label-tag">Published</h3>
						</div>

						<div class="item1">
							<h3 class="t-op-nextlvl">Article 68</h3>
							<h3 class="t-op-nextlvl">1.9k</h3>
							<h3 class="t-op-nextlvl">390</h3>
							<h3 class="t-op-nextlvl label-tag">Published</h3>
						</div>

						<div class="item1">
							<h3 class="t-op-nextlvl">Article 67</h3>
							<h3 class="t-op-nextlvl">1.2k</h3>
							<h3 class="t-op-nextlvl">580</h3>
							<h3 class="t-op-nextlvl label-tag">Published</h3>
						</div>

						<div class="item1">
							<h3 class="t-op-nextlvl">Article 66</h3>
							<h3 class="t-op-nextlvl">3.6k</h3>
							<h3 class="t-op-nextlvl">160</h3>
							<h3 class="t-op-nextlvl label-tag">Published</h3>
						</div>

						<div class="item1">
							<h3 class="t-op-nextlvl">Article 65</h3>
							<h3 class="t-op-nextlvl">1.3k</h3>
							<h3 class="t-op-nextlvl">220</h3>
							<h3 class="t-op-nextlvl label-tag">Published</h3>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

	

app/views/admin/news/new.html.erb
<h1>New News</h1>


<%= render 'form' %>

<%= link_to 'Back', admin_news_index_path %>

app/views/admin/news/show.html.erb
<h1>Show News</h1>

<div class="sidebar">


      <form class="d-flex" role="search">
      <%= form_tag search_admin_news_index_path method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search news..." , class:"form-control me-2" %>
        <%= submit_tag "Search", class:"btn btn-outline-success" %>
      <% end %>
      </form>
  <a href="#">Field</a>
  <a href="#">City</a>
  <a href="#">Category</a>
  <a href="#">News</a>
  <a href="#">State</a>

  <%if user_signed_in?%>
  <%= link_to "logout" ,destroy_user_session_path,data: {"turbo-method": :delete}  ,class:"nav-link" %>
  <%else%>
  <%= link_to "login" ,new_user_session_path  ,class:"nav-link" %>

    <%end%>
</div>

<p><strong>Title:</strong> <%= @news.title %></p>
<p><strong>Headlines:</strong> <%= @news.headlines %></p>
<p><strong>Short Description:</strong> <%= @news.short_description %></p>
<p><strong>Description:</strong> <%= @news.description %></p>


<% @news.images.each do |image| %>
    <%= image_tag image %>
  <% end %>
  <% @news.videos.each do |video_attachment| %>
    <video controls width="640" height="360">
      <source src="<%= rails_blob_path(video_attachment, disposition: :attachment) %>" type="<%= video_attachment.content_type %>">
      Your browser does not support the video tag.
    </video>
  <% end %>
  
  

<%= link_to 'Edit', edit_admin_news_path(@news) %> |
<%= link_to 'Back', admin_news_index_path %>