config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get '/categories/:category_id/news/:news_id', to: 'categories#news' ,as: 'categor_news'

    resources :categories
    resources :news

  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get 'homes/index'
  get 'homes/:id', to: 'homes#show', as: 'show_home'

  root 'homes#index'

  namespace :editor do
    
    resources  :news
  end



  namespace :admin do
   
    
    resources :categories

    get '/categories/:category_id/news/:news_id', to: 'categories#news' ,as: 'categor_news'

    resources :news do
      collection do
        get :search
      end
    end
    

   
  resources :states do
      resources :cities
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "news#index"

  
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :state
  belongs_to :city
  belongs_to :category
  has_many_attached :images
   has_many_attached :videos

  def image_urls
    images.map do |image|
      Rails.application.routes.url_helpers.rails_blob_url(image, only_path: true)
    end
  end
  # validates :title, presence: { message: "Title can't be blank" },
  # length: { maximum: 50, message: "Title is too long (maximum is 50 characters)" }
  # validates :headlines, presence: { message: "Title can't be blank" },
  # length: { maximum: 50, message: "Title is too long (maximum is 50 characters)" }


end

app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
  before_action :authenticate_user!
 before_action :check_admin_and_editor_roles
    before_action :set_news, only: [:show, :edit, :update, :destroy]
  
    def index
      @news = News.all
     
      # render json: @news, methods: [:image_urls]
    end
  
    def new
      @news = News.new
    end
  
    def create
      
      @news = News.create(news_params)
  
      
        redirect_to admin_news_index_path, notice: 'News was successfully created.'
      
     
    end
  
    def show
    end
  
    def edit
    end
  
    def update
      if @news.update(news_params)
        redirect_to admin_news_index_path, notice: 'News was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @news.destroy
      redirect_to admin_news_index_path, notice: 'News was successfully destroyed.'
    end
  
    private
  
    def set_news
      @news = News.find(params[:id])
    end
  
    def news_params
      params.require(:news).permit(:title, :headlines, :short_description, :description,:state_id ,:city_id ,:category_id, images: [] , videos: [])
    end

    def check_admin_and_editor_roles
      check_role
    end
  def check_role
    unless current_user.has_role?(:admin)
      redirect_to root_path, alert: "You are not authorized to access the editor panel."
    end
  end
end

app/controllers/api/news_controller.rb
class Api::NewsController < ApplicationController

     def index
      @news = News.all
     
      render json: @news, methods: [:image_urls]
    end

    def show
      @news = News.find(params[:id])
      render json: @news, methods: [:image_urls]


    end
 
end

app/controllers/editor/news_controller.rb
class Editor::NewsController < ApplicationController
  before_action :authenticate_user!
 before_action :check_admin_and_editor_roles
  
  def index
   
    @news = News.all
   
  end

  def new
    @news = News.new
  end

  def create
    
    @news = News.create(news_params)

    
      redirect_to editor_news_index_path, notice: 'News was successfully created.'
    
   
  end

  def show
    @news = News.find(params[:id])

  end

  def edit
    @news = News.find(params[:id])

  end

  def update
    if @news.update(news_params)
      redirect_to editor_news_index_path, notice: 'News was successfully updated.'
    else
      render :edit
    end
  end



  def news_params
    params.require(:news).permit(:title, :headlines, :short_description, :description,:state_id ,:city_id ,:category_id, images: [])
  end
 
  def check_admin_and_editor_roles
    check_role
  end
def check_role
    unless current_user.has_role?(:editor)
      redirect_to root_path, alert: "You are not authorized to access this page."
    end
  end



 
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/helpers/api/news_helper.rb
module Api::NewsHelper
end

app/helpers/editor/news_helper.rb
module Editor::NewsHelper
end

app/views/editor/news/edit.html.erb
<%= form_with(model: @news, url: @news.new_record? ? admin_news_index_path : admin_news_path(@news), method: @news.new_record? ? :post : :patch) do |f| %>
 
  
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  
    <div class="field">
      <%= f.label :headlines %>
      <%= f.text_field :headlines %>
    </div>
  
    <div class="field">
      <%= f.label :short_description %>
      <%= f.text_area :short_description %>
    </div>
  
    

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>


    <div  class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div  class="field">
    <%= f.label :state_id %><br>
    <%= f.collection_select :state_id, State.all, :id, :name %>
  </div>
  <div>
       
    


      <%= f.label :city_id %><br>
      <%= f.collection_select :city_id,  City.all, :id, :name %>
    </div>
  

    <div>
         <%= f.label :images, 'Upload Images' %>
           <%= f.file_field :images, multiple: true %>
      </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  

app/views/editor/news/index.html.erb
<h1>Editor::News#index</h1>
<p>Find me in app/views/editor/news/index.html.erb</p>


<table  class="table table-success table-striped">
  <thead>
    <tr>
      <th  scope="col">Title</th>
      <th  scope="col">Headlines</th>
      <th  scope="col">created_at</th>
      <th  scope="col">Actions</th>

    </tr>
  </thead>
  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.headlines %></td>
        <td><%= display_ist_time(news.created_at) %></td>

        <td>
          <%= link_to 'Show', editor_news_path(news) %>
          <%= link_to 'Edit', edit_editor_news_path(news) %>
          
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

<%= link_to 'New News', new_editor_news_path %>

app/views/editor/news/new.html.erb
<%= form_with(model: @news, url: @news.new_record? ? editor_news_index_path : editor_news_path(@news), method: @news.new_record? ? :post : :patch) do |f| %>
 
  
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  
    <div class="field">
      <%= f.label :headlines %>
      <%= f.text_field :headlines %>
    </div>
  
    <div class="field">
      <%= f.label :short_description %>
      <%= f.text_area :short_description %>
    </div>
  
    

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>


    <div  class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div  class="field">
    <%= f.label :state_id %><br>
    <%= f.collection_select :state_id, State.all, :id, :name %>
  </div>
  <div>
       
    


      <%= f.label :city_id %><br>
      <%= f.collection_select :city_id,  City.all, :id, :name %>
    </div>
  

    <div>
         <%= f.label :images, 'Upload Images' %>
           <%= f.file_field :images, multiple: true %>
      </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  

app/views/editor/news/show.html.erb
<div class="container">
  <h1>Show News</h1>
  <p><strong>Title:</strong> <%= @news.title %></p>
  <p><strong>Headlines:</strong> <%= @news.headlines %></p>
  <p><strong>Short Description:</strong> <%= @news.short_description %></p>
  <p><strong>Description:</strong> <%= @news.description %></p>

  <% @news.images.each do |image| %>
    <%= image_tag image, class: "news-image" %>
  <% end %>

  <p><%= link_to 'Edit', edit_editor_news_path(@news) %> |
     <%= link_to 'Back', editor_news_index_path %></p>
</div>