config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get '/categories/:category_id/news/:news_id', to: 'categories#news' ,as: 'categor_news'

    resources :categories
    resources :news

  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get 'homes/index'
  get 'homes/:id', to: 'homes#show', as: 'show_home'

  root 'homes#index'

  namespace :editor do
    
    resources  :news
  end



  namespace :admin do
   
    
    resources :categories

    get '/categories/:category_id/news/:news_id', to: 'categories#news' ,as: 'categor_news'

    resources :news do
      collection do
        get :search
      end
    end
    

   
  resources :states do
      resources :cities
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "news#index"

  
end

app/models/state.rb
class State < ApplicationRecord
    has_many :cities, dependent: :destroy
    has_many :news
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController
  before_action :authenticate_user!
 before_action :check_admin_and_editor_roles
   
  
      def index
        @states = State.all
      end
  
      def show
        @state = State.find(params[:id])
      end
  
      def new
        @state = State.new
      end
  
      def create
        @state = State.new(state_params)
        if @state.save
          redirect_to admin_state_path(@state), notice: 'State was successfully created.'
        else
          render :new
        end
      end
  
      def edit
        @state = State.find(params[:id])
      end
  
      def update
        @state = State.find(params[:id])
        if @state.update(state_params)
          redirect_to admin_state_path(@state), notice: 'State was successfully updated.'
        else
          render :edit
        end
      end
  
      def destroy
        @state = State.find(params[:id])
        @state.destroy
        redirect_to admin_states_path, notice: 'State was successfully destroyed.'
      end
  
      private
  
      def state_params
        params.require(:state).permit(:name)
      end

    def check_admin_and_editor_roles
      check_role
    end
  def check_role
    unless current_user.has_role?(:admin)
      redirect_to root_path, alert: "You are not authorized to access the editor panel."
    end
  end
  
  
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_with(model: @state, url: @state.new_record? ? admin_states_path : admin_state_path(@state), local: true) do |form| %>
    <% if @state.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@state.errors.count, 'error') %> prohibited this state from being saved:</h2>
  
        <ul>
          <% @state.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/admin/states/index.html.erb
<h1>States</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= link_to 'Show', admin_state_path(state) %></td>
        <td><%= link_to 'Edit', edit_admin_state_path(state) %></td>
        <td><%= link_to 'Destroy', admin_state_path(state), method: :delete, data: { confirm: 'Are you sure?' }
         %></td>
        <td><%= link_to 'new city', new_admin_state_city_path(state) %></td>

         
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_admin_state_path %>

app/views/admin/states/new.html.erb
    

<h1><%= action_name.capitalize %> State</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_states_path %>

app/views/admin/states/show.html.erb
<h1>State Details</h1>

<p><strong>Name:</strong> <%= @state.name %></p>

<%= link_to 'Edit', edit_admin_state_path(@state) %> |
<%= link_to 'Back', admin_states_path %>